### ISSUE TITLE
pip install with python3.4 fails

### ISSUE THREAD

**Issue by dwoz** [bots-edi/bots#42]
Related to [Issue 24](https://github.com/bots-edi/bots/issues/24) trying to pip install with python3.4 fails.

```
Collecting bots
  Downloading bots-3.3.0.tar.gz (479kB)
    100% |████████████████████████████████| 481kB 940kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h3/mvmh74hd53g7q9knk4mql2s80000gn/T/pip-build-c_t106tp/bots/setup.py", line 54, in <module>
        '\n\n' +
      File "/private/var/folders/h3/mvmh74hd53g7q9knk4mql2s80000gn/T/pip-build-c_t106tp/bots/setup.py", line 46, in read
        with io.open(fn, encoding=kwargs.get('encoding', 'utf8')) as fd:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/h3/mvmh74hd53g7q9knk4mql2s80000gn/T/pip-build-c_t106tp/bots/readme.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h3/mvmh74hd53g7q9knk4mql2s80000gn/T/pip-build-c_t106tp/bots/
```

**Comment by aaronbains** [comment]
I am experiencing the same error with Python 3.5.6

**Comment by WKaz** [comment]
This fork is inactive. We've moved the development to https://gitlab.com/bots-ediint/. More information about the project is gathered here: https://bots-edi.org/.
