### ISSUE TITLE
Bots Windows-installer is outdated

### ISSUE THREAD

**Issue by bf-ckiendl** [bots-edi/bots#67]
The Windows-installer is for Bots 3.2.0.
I coincidentally saw at PyPi that there is a version 3.3.0, but I cannot update my installation because...

```
Collecting bots
  Downloading https://files.pythonhosted.org/packages/f2/b0/897cccaafb5a2f6e6ec26b4248cfd2bfc2ba680d58cb4e1ad898a96dbe27/bots-3.3.0-py2-none-any.whl (551kB)
     |################################| 552kB 595kB/s
Installing collected packages: bots
  Found existing installation: bots 3.2.0
ERROR: Cannot uninstall 'bots'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

This means that, in practice, there is no documentation on how to install the current Bots on Windows.
In combination with #66, it means that there is no documentation on how to install a _functioning_ Bots on Windows at all.

I'll see if I can remove the distutils Bots installation and reinstall it through pip with the installer-based dependencies intact, but even if that works, it is far from ideal.

**Comment by bf-ckiendl** [comment]
Word of advice for similarly afflicted people: pip's --ignore-installed does **not** work, it leads to `django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named psycopg2`.

**Comment by eino-makitalo** [comment]
Also missing readme.rst

`(env) c:\myvirtualenv\>**pip install bots**
Downloading/unpacking bots
  Running setup.py (path:D:\meyer\env\build\bots\setup.py) egg_info for package
bots
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "D:\meyer\env\build\bots\setup.py", line 54, in <module>
        '\n\n' +
      File "D:\meyer\env\build\bots\setup.py", line 46, in read
        with io.open(fn, encoding=kwargs.get('encoding', 'utf8')) as fd:
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\meyer\\env\\bui
ld\\bots\\readme.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "D:\meyer\env\build\bots\setup.py", line 54, in <module>

    '\n\n' +

  File "D:\meyer\env\build\bots\setup.py", line 46, in read

    with io.open(fn, encoding=kwargs.get('encoding', 'utf8')) as fd:

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\meyer\\env\\build\\
bots\\readme.rst'

----------------------------------------
Cleaning up...`

**Comment by WKaz** [comment]
This fork is inactive. We've moved the development to https://gitlab.com/bots-ediint/. More information about the project is gathered here: https://bots-edi.org/.
