### ISSUE TITLE
No module named 'enveloperecords'

### ISSUE THREAD

**Issue by aoplnx** [bots-edi/bots#81]
Using python 3.4 I am getting the below messages. Any help and or hint will be appreciated

Traceback (most recent call last): File "/usr/local/lib/python3.4/site-packages/bots/transform.py", line 85, in _translate_one_file edifile.checkforerrorlist() # no exception if infile has been lexed and parsed OK else raises an error File "/usr/local/lib/python3.4/site-packages/bots/message.py", line 48, in checkforerrorlist raise botslib.MessageError(''.join(self.errorlist)) bots.botslib.MessageError: Traceback (most recent call last): File "/usr/local/lib/python3.4/site-packages/bots/inmessage.py", line 43, in parse_edi_file ediobject.initfromfile() File "/usr/local/lib/python3.4/site-packages/bots/inmessage.py", line 75, in initfromfile self.messagegrammarread(typeofgrammarfile='grammars') File "/usr/local/lib/python3.4/site-packages/bots/message.py", line 60, in messagegrammarread self.defmessage = grammar.grammarread(self.ta_info['editype'], self.ta_info['messagetype'], typeofgrammarfile) File "/usr/local/lib/python3.4/site-packages/bots/grammar.py", line 32, in grammarread messagegrammar = classtocall(typeofgrammarfile='grammars', editype=editype, grammarname=grammarname) File "/usr/local/lib/python3.4/site-packages/bots/grammar.py", line 102, in __init__ self.module, self.grammarname = botslib.botsimport(typeofgrammarfile, editype, grammarname) File "/usr/local/lib/python3.4/site-packages/bots/botslib.py", line 496, in botsimport raise _exception bots.botslib.BotsImportError: No import of module "/usr/local/lib/python3.4/site-packages/bots/usersys/grammars/x12/x12": No module named 'enveloperecords'

**Comment by WKaz** [comment]
This fork is inactive. We've moved the development to https://gitlab.com/bots-ediint/. More information about the project is gathered here: https://bots-edi.org/.

Please test your issue with the version 4.0, links above. If the issue still occurs, open an issue at https://gitlab.com/groups/bots-ediint/-/issues.
