### ISSUE TITLE
Preparing metadata (setup.py) ... error   error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by dinesh1299** [bots-edi/bots#86]
I'm getting this issue while installing bots

pip install bots
Collecting bots
  Downloading bots-3.3.0.tar.gz (479 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 479.0/479.0 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-uook0ulr/bots_df9a6eb007184fe698c8ecaf7e57dd70/setup.py", line 53, in <module>
          read('readme.rst') +
        File "/tmp/pip-install-uook0ulr/bots_df9a6eb007184fe698c8ecaf7e57dd70/setup.py", line 46, in read
          with io.open(fn, encoding=kwargs.get('encoding', 'utf8')) as fd:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-uook0ulr/bots_df9a6eb007184fe698c8ecaf7e57dd70/readme.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Aclopes** [comment]
I have the same problem.
Is there any package that needs to be installed first?

**Comment by WKaz** [comment]
This fork is inactive. We've moved the development to https://gitlab.com/bots-ediint/. More information about the project is gathered here: https://bots-edi.org/.
